### ISSUE TITLE
How to change the World and Agents

### ISSUE THREAD

**Issue by FurkanEdizkan** [TempleRAIL/pedsim_ros_with_gazebo#3]
Hello, I have been having problem with 

1. Where to change in order to change the world file
2. Change pedsim agents spawn location
3. Change agent groups (I want to group them differently)
4. Change agents models (I want some agent to represent human, some animal, some other robots)
5. Change agent speeds (I want to make them move in different speeds)
6. Change agents patrol positions

 
I have checked the references repository however inside references repository link for documentation is broken, so I am unable to find solution.

Any direction to where to look and what to change/fix would be great help

Thank you beforehand

Edit 1:

I have read solved issues, I saw that we need to change the scenario file with .xml to change number of agent, their spawn positions, their grouping behavior and patrol positions (I think, if I am mistaken please fix).

I saw that there was a tutorial link however it seem it is broken and not working -> [pedsim documentation](http://pedsim.silmaril.org/documentation/libpedsim/latest/demoapp_scenario.html)

**Comment by zzuxzt** [comment]
Sorry, I just noticed this issue now. Probably because there were too many issues posted from you at the same time.

I am not sure you still need some guidance on it since you said you have gotten good results from our [drl_vo ](https://github.com/TempleRAIL/drl_vo_nav) navigation policy. But in simple terms, if you want to change the world and agent, you need to manually create the scenario file (i.e. **.xml) and configure the positions of static objects and the groups and positions of the agents.

Since I have been busy with some personal issues these days, I will update some detailed instructions on how to modify these things later when I am less busy.

**Comment by FurkanEdizkan** [comment]
I have found the the documentation with [wayback machine](https://wayback-api.archive.org/). Thank you for answering. 
Still some explanation on how to tweak the settings would be great.
