### ISSUE TITLE
pedestrian force design

### ISSUE THREAD

**Issue by yimengweima0** [TempleRAIL/pedsim_ros_with_gazebo#7]
Hello, thank you very much for your work. Could you please provide the code for designing the forces between pedestrians and the robot when evaluating the navigation algorithm, using the latest branch of ped_agent.cpp? After testing, the success rate of your algorithm is only 30. Thank you! @zzuxzt

**Comment by yimengweima0** [comment]
Could you please assist me in resolving them? I would really appreciate your guidance. Thank you @zzuxzt

**Comment by yimengweima0** [comment]
Could you please assist me in resolving them? I would really appreciate your guidance. Thank you @zzuxzt

**Comment by zzuxzt** [comment]
This package already contains all the simulator code. To change the social force parameters, you can modify the ped_agent.cpp.

I do not know how you tested it. Note that modifying the maximum velocity (e.g. vz_min, vz_max) will also affect the performance. In summary, the evaluation depends on many factors, such as your computer performance, your configuration, the Gazebo timing, and the interaction state of the Gazebo environment.

**Comment by yimengweima0** [comment]
Thank you for your response.

Regarding your code, I didn’t make any modifications. I only followed your suggestion and adjusted the angular velocity vz_min and vz_max to -0.7 and 0.7, respectively. My Gazebo realtime_factor is set to 1, and I’ve set the test target points as the four shown in the figure, running 10 cyclic tests.
![image](https://github.com/user-attachments/assets/f7d48331-5776-4973-bb91-0a14dd24faef)


Since I’m using the default parameters from the drl_vo branch in ped_agent.cpp, and the test code is also based on your shared code, 
![image](https://github.com/user-attachments/assets/9d67c0dc-37a1-4f1c-93ef-bb03e82c60e5)
I feel that the low success rate might be due to a couple of reasons: one possibility is that the target points are too far apart, and another is that the latest branch you provided may not contain the same force evaluation code between the robot and the pedestrians as described in your paper in ped_agent.cpp. "Because even when the robot is stationary, pedestrians might still collide with it. Or perhaps the navigation code still needs further tuning.

Could you please assist me in resolving them? I would really appreciate your guidance. Thank you. @zzuxzt

**Comment by zzuxzt** [comment]
Note that my suggestion regarding angular velocity will degrade navigation performance in simulation, since you said you only used odometry information and discovered a large wiggling behavior of the robot. Additionally, it is important to ensure that the initial state is the same for each test, since this is an interactive simulation and the robot's movements affect the simulation state in real-time. In other words, each different robot action will result in a different simulation test. Increasing the number of tests and ensuring the same simulation state will provide a more accurate evaluation.
Yes, long distance goal points will also increase the collision rate, because one collision will result in failure. 
Since the current social force model is not perfect enough, even if social forces exist, collisions with pedestrians themselves or with the robot may occur. If you feel that the social force between the robot and the pedestrian is too small, you can try to increase the robotPosDiffScalingFactor in the code. It will improve the situation you are facing.

**Comment by yimengweima0** [comment]
Ok,Thank you for your response.
